sudo: false
language: erlang
otp_release:
  - 18.3
services:
  - redis-server
before_install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 
  - chmod +x rebar3
script: "./rebar3 eunit && ./rebar3 ct"
